# -*- coding: utf-8 -*-
"""
VMQ 778-son to'liq korpusi uchun qidiruv teglari va case_type xaritasi.

Legal matn rasmiy o'zbek tilida. Foydalanuvchi esa "telefonim bloklandi",
"черный список", "phone blocked" deb yozadi. Shu sababli har bir muhim band va
ta'rifga real foydalanuvchi iboralari (uz lotin), rus va ingliz sinonimlari
qo'shiladi — BM25 / embedding qidiruvi legal bandni oddiy savoldan topadi.
Teglar normallashtiriladi (kirill -> lotin, apostroflar olib tashlanadi), shuning
uchun bu yerda qulay yozuvda yoziladi.
"""

_HISTORY = [
    "qachon o'zgargan", "o'zgartirish", "tahrir", "tahririda", "kuchga kirgan",
    "kiritilgan", "chiqarilgan", "o'z kuchini yo'qotgan", "eski tahrir",
    "когда изменен", "когда изменили", "изменился", "изменения", "редакция", "утратил силу",
    "amendment", "amended", "history", "when changed",
]

TAGS = {
    # --- qaror ---------------------------------------------------------------
    "qaror:1": ["nizom tasdiqlangan", "778-son qaror", "постановление 778", "resolution 778"],
    "qaror:2": ["2019-yil 1-noyabr", "2019-yil 1-dekabr", "bepul ro'yxatga olish davri",
                "o'tish davri", "переходный период", "transition period"],
    # --- 2-band: ta'riflar -----------------------------------------------------
    "nizom:2:gsma": ["gsma nima", "gsma bazasi", "что такое gsma", "what is gsma",
                     "tac taqsimlash", "ishlab chiqaruvchi va model"],
    "nizom:2:imei": ["imei nima", "imei kod", "15 raqam", "ikki imei", "что такое imei",
                     "what is imei", "imei number", "ikkita imei kod"],
    "nizom:2:msisdn": ["msisdn nima", "telefon raqami", "abonent raqami", "номер абонента",
                       "phone number msisdn"],
    "nizom:2:sim-karta": ["sim karta nima", "sim-карта", "sim card"],
    "nizom:2:sms": ["sms nima", "sms xabar", "sms message"],
    "nizom:2:ussd": ["ussd nima", "ussd so'rov", "ussd запрос", "ussd code"],
    "nizom:2:abonent": ["abonent kim", "абонент", "subscriber"],
    "nizom:2:import qiluvchi": ["import qiluvchi kim", "импортер", "importer"],
    "nizom:2:imei-kodlar maʼlumotlar bazasi": ["imei bazasi", "база imei", "imei database"],
    "nizom:2:oq roʻyxat": ["oq ro'yxat", "white list", "белый список", "что такое белый список", "ro'yxatdan o'tgan telefon",
                          "telefon ishlaydi", "registered imei"],
    "nizom:2:qora roʻyxat": ["qora ro'yxat nima", "telefon bloklandi", "imei blacklist",
                            "telefon ishlamayapti", "cloned imei", "unregistered imei",
                            "черный список imei", "что такое черный список", "телефон заблокирован", "phone blocked",
                            "blacklist", "aloqa cheklandi", "sms ogohlantirish"],
    "nizom:2:kul rang roʻyxat": ["kulrang ro'yxat", "kul rang ro'yxat", "grey list", "gray list",
                                "серый список imei", "что такое серый список", "серый список",
                                "30 kun", "60 kun", "norezident 60 kun",
                                "qancha vaqt turadi", "vaqtincha ishlaydi", "registratsiyasiz ishlaydi",
                                "сколько дней работает без регистрации",
                                "how long without registration"],
    "nizom:2:bogʻlangan oq roʻyxat": ["bog'langan oq ro'yxat", "imei msisdn", "imei raqamga bog'langan",
                                     "faqat eski raqam bilan ishlaydi", "привязанный белый список",
                                     "linked white list", "imei bound to number"],
    "nizom:2:mobil qurilma hujjatlari": ["qurilma hujjatlari", "quti", "kafolat taloni",
                                        "texnik pasport", "документы устройства", "device documents"],
    "nizom:2:klonlangan imei-kod": ["klonlangan imei nima", "klon imei", "cloned imei",
                                   "клонированный imei", "dublikat imei", "duplicate imei"],
    "nizom:2:mobil qurilmalar": ["mobil qurilma nima", "мобильное устройство", "mobile device"],
    "nizom:2:aniqlanmagan imei-kod": ["aniqlanmagan imei nima", "imei gsma talabiga mos emas",
                                     "invalid imei", "неопределенный imei", "unknown imei"],
    "nizom:2:mobil aloqa operatori": ["mobil operator", "оператор связи", "mobile operator"],
    "nizom:2:tizim operatori": ["tizim operatori kim", "uzimei", "оператор системы", "system operator"],
    "nizom:2:imei-kodlarni tekshirish": ["imei tekshirish", "проверка imei", "imei check",
                                        "o'g'irlangan telefon aniqlash"],
    "nizom:2:mobil qurilmalarni roʻyxatga olish": ["ro'yxatga olish nima", "регистрация устройства",
                                                  "device registration"],
    "nizom:2:tizim roʻyxatga oluvchisi": ["ro'yxatga oluvchi kim", "регистратор", "registrar",
                                         "diler", "ro'yxatga olish punkti"],
    "nizom:2:fuqaroligi boʻlmagan shaxslar": ["fuqaroligi yo'q", "апатрид", "stateless person"],
    "nizom:2:chet davlat fuqarosi": ["chet el fuqarosi", "xorijlik", "иностранец", "foreigner",
                                    "norezident"],
    "nizom:2:rouming": ["rouming nima", "роуминг", "roaming"],
    "nizom:2:mobil qurilmalarni xalqaro oʻziga xos identifikatsiya kodlari boʻyicha roʻyxatga olish tizimi": [
        "uzimei tizimi", "tizim nima", "система регистрации imei", "imei registration system"],
    "nizom:2:tarmoq hodisasi": ["tarmoq hodisasi nima", "birinchi ulanish", "sim qo'yilgan kun",
                                "сетевое событие", "network event", "first network event"],
    "nizom:2:tac": ["tac nima", "imei birinchi 8 raqam", "type allocation code", "что такое tac"],
    "nizom:2:yashash guvohnomasi": ["yashash guvohnomasi", "вид на жительство", "residence permit"],
    # --- Nizom bandlari -------------------------------------------------------
    "nizom:1": ["nizom nima haqida", "qaysi qurilmalar", "область применения", "scope"],
    "nizom:3": ["tizim vazifasi", "ro'yxatlar", "назначение системы", "system purpose"],
    "nizom:4": ["imei tekshirish tizim orqali"],
    "nizom:5": ["sotib olishdan oldin tekshirish", "imei holatini tekshirish", "uzimei.uz",
                "sms ussd so'rov bepul", "проверить imei перед покупкой", "check imei before buying",
                "o'g'irlangan telefonni sotib olmaslik"],
    "nizom:6": ["imei ro'yxatga olish tartibi", "hozirgi tartib", "amaldagi tartib",
                "ro'yxatdan o'tkazish majburiy", "registratsiya majburiymi", "rouming istisno",
                "регистрация обязательна", "is registration mandatory", "roaming exemption"],
    "nizom:6.1": ["do'kondan olingan telefon", "do'kon javobgar", "sotuvchi javobgar",
                  "chakana savdo", "kim registratsiya qilishi kerak", "magazin",
                  "магазин отвечает за регистрацию", "phone sold in uzbekistan",
                  "who is responsible for registering", "retail seller responsible"],
    "nizom:7": ["klonlangan imei registratsiya qilinadimi", "aniqlanmagan imei ro'yxatga olinmaydi",
                "клон imei не регистрируется", "cloned imei cannot be registered"],
    "nizom:8": ["ro'yxatga olish tartibi", "hozirgi tartib", "qaysi qurilmalar ro'yxatdan o'tadi", "murojaat orqali ro'yxatga olish",
                "какие устройства регистрируются", "which devices must be registered"],
    "nizom:9": ["qayta ro'yxatdan o'tkazish", "avval registratsiya qilingan telefon",
                "qayta registratsiya kerakmi", "повторная регистрация", "re-register phone",
                "sim almashtirsa"],
    "nizom:10": ["maxsus tartib", "favqulodda vaziyat", "xavfsizlik organlari", "mudofaa",
                 "особый порядок", "special procedure security"],
    "nizom:10.1": ["diplomatik vakolatxona", "elchixona", "konsullik", "diplomatik pochta",
                   "diplomatik servis xizmati", "дипломатическое представительство",
                   "посольство", "embassy", "consulate", "diplomatic mission"],
    "nizom:10.2": ["sud qarori", "davlat egaligi", "majburiy ijro byurosi", "davlat ijrochisi",
                   "конфискованные устройства", "court decision", "confiscated devices"],
    "nizom:11": ["import qilingan telefon qachon registratsiya", "im-40", "erkin muomala",
                 "uch kun", "import partiyasi", "импорт регистрация", "imported phone registration"],
    "nizom:12": ["eksport", "экспорт", "export devices"],
    "nizom:13": ["import qiluvchi qayerda ro'yxatdan o'tkazadi", "yagona portal", "my.gov.uz",
                 "ЕПИГУ", "importer registration channels"],
    "nizom:14": ["byd", "bojxona yuk deklaratsiyasi", "byd 31-ustun", "byd mos kelmasa",
                 "bojxona kirim orderi", "partiya ro'yxatga olinmaydi", "rad etish", "qayta murojaat",
                 "o'n kun", "ishlab chiqaruvchi tac sertifikat", "гтд не совпадает", "отказ в регистрации",
                 "customs declaration does not match", "what happens if customs declaration data does not match",
                 "batch rejected", "telefonni chetdan olib keldim", "bojxona", "deklaratsiya",
                 "import phone uzbekistan"],
    "nizom:15": ["anketa qabul qilish", "anketa topshirish"],
    "nizom:16": ["nechta qurilma", "cheklanmagan", "количество устройств"],
    "nizom:17": ["ortiqcha hujjat talab qilinmaydi", "лишние документы"],
    "nizom:18": ["idoralararo so'rov", "межведомственный запрос"],
    "nizom:19": ["noto'g'ri ma'lumot javobgarlik", "ответственность за недостоверные данные"],
    "nizom:20": ["necha kunda ro'yxatga olinadi", "uch ish kuni", "срок регистрации импорт",
                 "registration time importer"],
    "nizom:21": ["hisob taqdim etish", "счет на оплату"],
    "nizom:22": ["to'lov 10 ish kuni", "oq ro'yxatga kiritish", "xabardor qilish", "оплата импортер"],
    "nizom:23": ["ikkinchi imei", "ikkinchi slot", "ikki simli telefon", "dual sim", "*#06#",
                 "esim", "второй imei", "second imei", "2019 gacha ro'yxatdan o'tgan",
                 "eski telefon", "avtomatik ro'yxatga olingan"],
    "nizom:24": ["o'zbekistonda sotib olingan telefon", "do'kondan olgan telefonni ro'yxatdan o'tkazish",
                 "jismoniy shaxs ro'yxatga olishi shart emas", "купил в узбекистане",
                 "bought in uzbekistan"],
    "nizom:25": ["chetdan olib kelingan telefon", "jismoniy shaxs sxemasi"],
    "nizom:26": ["30 kun ichida ro'yxatdan o'tkazish", "registratsiya muddati", "pochta orqali kelgan telefon",
                 "kuryer", "срок регистрации 30 дней", "registration deadline 30 days"],
    "nizom:27": ["sms ogohlantirish", "5 kun oldin", "xabar beriladi", "уведомление sms",
                 "warning sms"],
    "nizom:28": ["fuqaro ro'yxatdan o'tkazish", "jshshir", "mobil-id", "elektron raqamli imzo",
                 "biometrik", "sayt orqali", "how citizen registers", "гражданин регистрация"],
    "nizom:28.1": ["chet el fuqarosi ro'yxatdan o'tkazish", "norezident", "yashash guvohnomasi",
                   "fuqaroligi yo'q shaxs", "biometrik harakatlanish hujjati", "иностранец регистрация imei",
                   "foreigner imei registration"],
    "nizom:29": ["qanday hujjat kerak", "anketa", "jshshir", "документы для регистрации",
                 "documents for registration"],
    "nizom:29.1": ["deklaratsiya to'ldirish", "bojsiz norma", "декларация", "customs declaration"],
    "nizom:30": ["anketa qabul", "yidxp"],
    "nizom:31": ["pochta orqali kelgan telefon", "kuryer orqali", "shtrix kod", "konvert",
                 "kalendar shtempel", "aliexpress", "почтовое отправление", "postal parcel"],
    "nizom:31.1": ["chegarani kesib o'tish", "bojsiz norma", "bojxona to'lovi", "pochta tekshiruvi",
                   "персонализация", "пересечение границы", "border crossing"],
    "nizom:31.2": ["me'yordan ortiq", "ko'p telefon olib keldim", "bojxona to'lovi", "boj",
                   "превышение нормы", "too many phones", "customs duty"],
    "nizom:32": ["ortiqcha hujjat talab qilinmaydi"],
    "nizom:33": ["idoralararo so'rov"],
    "nizom:34": ["noto'g'ri ma'lumot javobgarlik"],
    "nizom:35": ["necha soatda ro'yxatga olinadi", "uch ish soati", "срок регистрации 3 часа"],
    "nizom:36": ["hisob 1 soat"],
    "nizom:37": ["to'lovdan keyin oq ro'yxat", "после оплаты"],
    "nizom:38": ["ariza ko'rib chiqilayotganda ishlaydimi", "kulrang ro'yxatda turadi",
                 "aloqa cheklanmaydi"],
    "nizom:38.1": ["to'lov muddati", "o'n kun ichida to'lash", "telefon balansidan to'lash",
                   "срок оплаты", "payment deadline", "pay from phone balance"],
    "nizom:39": ["klonlangan imei aniqlansa", "qora ro'yxatga tushdi", "клон imei черный список",
                 "cloned imei blacklisted"],
    "nizom:42": ["to'lov miqdori", "narx", "tarif", "сколько стоит регистрация",
                 "registration fee"],
    "nizom:43": ["to'lov qayerga tushadi", "maxsus hisobvaraq", "куда идут платежи"],
    "nizom:44": ["har bir imei uchun alohida to'lov", "ikki imei uchun to'lov", "ikkita imei narxi",
                 "за каждый imei отдельно", "pay for each imei separately", "dual sim fee"],
    "nizom:45": ["tizim operatori huquqlari", "rad etish asosi", "uchinchi shaxs ma'lumoti",
                 "отказ в регистрации", "права оператора системы"],
    "nizom:46": ["tizim operatori majburiyatlari", "обязанности оператора"],
    "nizom:47": ["tizim operatori javobgarligi", "maxfiy axborot"],
    "nizom:48": ["boshqa idoralar bilan hamkorlik"],
    "nizom:49": ["huquqni muhofaza qilish organlari so'rovi", "mobil qurilmani to'xtatish",
                 "приостановление по запросу"],
    "nizom:49.1": ["tizim operatori qo'shimcha xizmatlar"],
    "nizom:49.2": ["ro'yxatdan o'tgan imei bekor qilinishi", "bekor qilish", "registratsiya bekor",
                   "to'lov qaytarilmaydi", "pul qaytariladimi", "sud qarori bilan bekor",
                   "аннулирование регистрации imei", "возврат оплаты", "registration cancelled",
                   "refund"],
    "nizom:49.3": ["shikoyat qilish", "qaror ustidan shikoyat", "shikoyat huquqi",
                   "обжаловать решение", "жалоба", "appeal decision", "complaint"],
    "nizom:50": ["nizomni buzganlik javobgarlik", "ответственность"],
    # --- ilovalar -------------------------------------------------------------
    "ilova:1": ["qurilma turlari", "qaysi qurilmalar ro'yxatdan o'tadi", "device categories",
                "категории устройств", "avtomatik ro'yxatga olinadigan qurilmalar"],
    "ilova:1:1": ["planshet", "tablet", "планшет"],
    "ilova:1:2": ["smartfon", "smartphone", "смартфон"],
    "ilova:1:3": ["oddiy telefon", "feature phone", "кнопочный телефон", "mobil telefon"],
    "ilova:1:4": ["cho'ntak kompyuter", "pda", "portable"],
    "ilova:1:5": ["knopkali telefon", "handheld", "кнопочный"],
    "ilova:1:6": ["dongle", "usb modem adapter", "адаптер"],
    "ilova:1:7": ["wlan router", "wifi router", "роутер", "router"],
    "ilova:1:8": ["iot", "iot qurilmalar qanday registratsiya qilinadi", "elektr hisoblagich",
                  "m2m", "internet of things", "умный счетчик"],
    "ilova:1:9": ["avtomobil", "transport vositasi", "vehicle", "машина sim"],
    "ilova:1:10": ["elektron kitob", "e-book", "электронная книга"],
    "ilova:1:11": ["gps treker", "gps tracker", "pos terminal", "aloqa moduli", "module", "трекер"],
    "ilova:1:12": ["noutbuk", "laptop", "connected computer", "ноутбук"],
    "ilova:1:13": ["modem", "модем"],
    "ilova:1:14": ["aqlli soat", "smart watch", "fitnes braslet", "wearable", "умные часы"],
    "ilova:2": ["import sxemasi", "importer scheme"],
    "ilova:3a": ["diplomatik anketa", "elchixona anketasi", "embassy form"],
    "ilova:3b": ["sud qarori anketasi", "davlat egaligi anketa"],
    "ilova:3v": ["ishlab chiqaruvchi anketasi", "manufacturer form"],
    "ilova:3g": ["import qiluvchi anketasi", "byd anketa", "importer form"],
    "ilova:4": ["jismoniy shaxs sxemasi", "individual scheme"],
    "ilova:5": ["anketa namunasi", "qo'shimcha imei anketa", "jismoniy shaxs anketasi"],
    "ilova:5a": ["anketa namunasi", "olib kirilgan qurilma anketasi", "jismoniy shaxs anketasi"],
    "ilova:6": ["imei registratsiya narxi", "tarif", "bhm 20%", "bhm 25%", "bhm 10%", "to'lov miqdori",
                "registratsiya qancha turadi", "har bir imei uchun", "rouming bepul", "diplomatik 20%",
                "import qiluvchi to'lovi", "ishlab chiqaruvchi to'lovi", "стоимость регистрации imei",
                "registration fee per imei", "how much does registration cost"],
}

# case_type: kb/src/taxonomy.py dagi CASE_TYPES kalitlari
CASE_TYPES = {
    "nizom:2:qora roʻyxat": "blokdan_chiqarish",
    "nizom:2:klonlangan imei-kod": "klon_imei",
    "nizom:2:aniqlanmagan imei-kod": "aniqlanmagan_imei",
    "nizom:2:bogʻlangan oq roʻyxat": "eski_qurilma",
    "nizom:2:imei-kodlarni tekshirish": "yoqotilgan_ogirlangan",
    "nizom:5": "yoqotilgan_ogirlangan",
    "nizom:7": "klon_imei",
    "nizom:39": "klon_imei",
    "nizom:11": "bojxona",
    "nizom:14": "bojxona",
    "nizom:29.1": "bojxona",
    "nizom:31": "bojxona",
    "nizom:31.1": "bojxona",
    "nizom:31.2": "bojxona",
    "nizom:23": "esim_ikkinchi_slot",
    "nizom:21": "tolov_tarif",
    "nizom:22": "tolov_tarif",
    "nizom:36": "tolov_tarif",
    "nizom:37": "tolov_tarif",
    "nizom:38.1": "tolov_tarif",
    "nizom:42": "tolov_tarif",
    "nizom:43": "tolov_tarif",
    "nizom:44": "tolov_tarif",
    "ilova:6": "tolov_tarif",
    "nizom:49": "blokdan_chiqarish",
    "nizom:49.3": "shikoyat",
}


def tags_for(key):
    """Birlik kaliti uchun teglar; tarixiy izohlar umumiy 'tarix' teglarini oladi."""
    if key.startswith("tarix:"):
        return list(_HISTORY) + list(TAGS.get(key, []))
    return list(TAGS.get(key, []))
